title: pg-migration-lint
description: Static analysis for PostgreSQL migration files
baseurl: /pg-migration-lint
url: https://robert-sjoblom.github.io
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
